version: "3.3"

networks:
  rb_default:
    driver: bridge

services:
  # source:
  #   image: papybretzel/ingesup-rb-source:latest
  #   build:
  #     context: ./source
  #   hostname: source-test.rb_default
  #   ports:
  #     - 4242:8080
  #   # labels:
  #   #   - "traefik.backend=ls"
  #   #   - "traefik.port=8080"
  #   #   - "traefik.frontend.rule=Host:ls.traefik"
  #   networks:
  #     rb_default:
  #       aliases:
  #         - source-test.rb_default

  backend:
     image: papybretzel/ingesup-rb-backend:latest
     build:
        context: ./backend
     hostname: backend.rb_default
     depends_on:
        - database
     ports:
        - 80:5000
     volumes:
        - ./backend:/usr/src/radiobretzel
        - /var/run/docker.sock:/var/run/docker.sock
     networks:
        rb_default:
           aliases:
             - backend.rb_default

  database:
     image: mongo
     hostname: mongo.rb_default
     # environment:
     #    - MONGO_INITDB_ROOT_USERNAME=app
     #    - MONGO_INITDB_ROOT_PASSWORD=S€cur3-P@$$
     networks:
        rb_default:
           aliases:
              - mongo.rb_default

  # proxy:
  #   image: traefik
  #   command: --web --docker --docker.domain=traefik --logLevel=DEBUG
  #   networks:
  #     radiobretzel:
  #       aliases:
  #         - traefik.traefik
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/null:/traefik.toml
