version: "3.3"

networks:
  radiobretzel_default:
    driver: bridge

services:
  source:
    command: ./advTest.liq
    image: radiobretzel/source:dev
    build:
      context: ./source/
      dockerfile: dockerfiles/dev
    ports:
      - 8080:8080
    volumes:
      - ./source/audio-test:/audio
      - ./source/scripts:/scripts
    networks:
      radiobretzel_default:
        aliases:
          - source.radiobretzel
    environment:
     - STREAM_MOUNTPOINT=channel
     - API_HOST=backend.radiobretzel
     - SOURCE_ID=dummy_id
     - SOURCE_TOKEN=dummy_token
    depends_on:
      - backend

  backend:
    command: ./run.py
    image: radiobretzel/backend:dev
    build:
      context: ./backend/
      dockerfile: dockerfiles/dev
    ports:
      - 8000:5000
    volumes:
      - ./backend:/usr/src/radiobretzel
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      radiobretzel_default:
        aliases:
          - backend.radiobretzel
