version: "3.3"

networks:
   main:
      driver: bridge
   sources:
      driver: bridge

services:
   backend:
      image: radiobretzel/backend:dev
      build:
         context: ./backend/
         dockerfile: dockerfiles/dev
      depends_on:
         - database
      ports:
         - 80:5000
      volumes:
         - ./backend/:/usr/src/rb_backend
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         main:
            aliases:
               - backend.main.radiobretzel
         sources:
            aliases:
               - backend.sources.radiobretzel
   database:
      image: mongo
      networks:
         main:
            aliases:
               - database.main.radiobretzel
   streaming:
      image: radiobretzel/stream:dev
      build:
         context: ./stream/
         dockerfile: dockerfiles/dev
      ports:
         - 8000:8000
      networks:
         sources:
            aliases:
               - streaming.sources.radiobretzel

   # Tools
   db_explorer:
      image: mongo-express
      ports:
         - 8081:8081
      depends_on:
         - database
      logging:
         driver: "none"
      environment:
         - ME_CONFIG_MONGODB_SERVER=database.main.radiobretzel
         - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      networks:
         main:
            aliases:
               - db-explorer.main.radiobretzel
