version: "3.3"

services:
  backend:
    command: test.liq
    image: radiobretzel/source:feature-1.1-Generate-audio-source
    build:
      context: ./source/
      dockerfile: dockerfiles/dev
    ports:
      - 8080:8080
    volumes:
      - ./source/scripts:/scripts
