version: "3.3"

networks:
  radiobretzel:
    driver: bridge

services:
  source:
    image: radiobretzel/source:dev-0.0.2
    build:
      context: ./source
      dockerfile: ./dockerfiles/dev-0.0.2
    hostname: source-test
    networks:
      radiobretzel:
        aliases:
          - source-test.radiobretzel

  stream:
    image: radiobretzel/stream:dev-0.0.2
    build:
      context: ./stream
      dockerfile: ./dockerfiles/dev-0.0.2
    hostname: stream-test
    ports:
      - 8000:8000
    networks:
      radiobretzel:
        aliases:
          - stream-test.radiobretzel
