version: '2'  
services:  
  icecast:
    build:
      context: ./icecast/
      dockerfile: Dockerfile
    volumes:
            - ./icecast/config:/etc/config
      - ./icecast/runIcecast:/runIcecast
    image: icecast-bretzel
    ports: 
      - "8000:8000"
    hostname: icecast.bretzel
    networks:
      radiobretzel:
        aliases:
          - icecast
          - icecast.bretzel

  liquidsoap:
    build:
      context: ./liquidsoap/
      dockerfile: Dockerfile
    volumes:
      - ./liquidsoap/ls/audio/fail.mp3:/ls/audio/fail.mp3
      - ./liquidsoap/ls/audio/test/test.mp3:/ls/audio/test.mp3
      - ./liquidsoap/scripts/test.liq:/test.liq
      - ./liquidsoap/scripts/runstream:/runstream
    image: liquidsoap-bretzel
    hostname: liquidsoap.bretzel
    depends_on:
      - "icecast"
    networks:
      radiobretzel:
        aliases:
          - liquidsoap
          - liquidsoap.bretzel

networks:
  radiobretzel:
    driver: bridge
    ipam:
      config:
      - subnet: 18.18.18.0/24 
