version: '2'
services:
  icecast:
    build:
      context: ./icecast/
      dockerfile: Dockerfile
    image: icecast-bretzel
    ports:
      - "8000:8000"
    hostname: icecast.bretzel
    networks:
      radiobretzel:
        aliases:
          - icecast
          - icecast.bretzel

  liquidsoap_test:
    build:
      context: ./liquidsoap/
      dockerfile: Dockerfile
    volumes:
      - ./liquidsoap/test:/home/liquy/var
    image: liquidsoap-bretzel
    hostname: liquidsoap.bretzel
    depends_on:
      - "icecast"
    networks:
      radiobretzel:
        aliases:
          - liquidsoap_test
          - liquidsoap_test.bretzel

  node:
    build:
      context: ./node/
      dockerfile: Dockerfile
    volumes:
      - ./node/server/src:/usr/src/app/src
    image: node-bretzel
    ports:
      - "80:8082"
    hostname: node.bretzel
    networks:
      radiobretzel:
        aliases:
          - node
          - node.bretzel
      nodetohost:
        aliases:
          - dockerhost
        ipv4_address: 18.18.19.2

networks:
  nodetohost:
    driver: bridge
    ipam:
      config:
        - subnet: 18.18.19.0/30
  radiobretzel:
    driver: bridge
    ipam:
      config:
      - subnet: 18.18.18.0/24
