version: "3.3"

networks:
  radiobretzel:
    driver: bridge

services:
  source:
    image: radiobretzel/source:dev
    command: "./test.liq"
    build:
      context: ./
      dockerfile: ./dockerfiles/dev
    volumes: 
      - ./../_data/audio/ok:/audio
      - ./scripts:/scripts
    hostname: source-test
    ports:
      - 4242:8080
    networks:
      radiobretzel:
        aliases:
          - source-test.radiobretzel

  stream:
    image: radiobretzel/stream:dev
    build:
      context: ./../stream
      dockerfile: ./dockerfiles/dev
    hostname: stream-test
    ports:
      - 8000:8000
    networks:
      radiobretzel:
        aliases:
          - stream-test.radiobretzel
