version: "3.3"

networks:
  radiobretzel:
    driver: bridge

services:
  source:
    image: radiobretzel/source:dev
    command: "./test.liq"
    build:
      context: ./
      dockerfile: ./dockerfiles/dev
    volumes: 
      - ./../_data/audio/ok:/audio
      - ./scripts:/scripts
    hostname: ls.traefik
    ports:
      - 4242:8080
    labels:
      - "traefik.backend=ls"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ls.traefik"
    networks:
      radiobretzel:
        aliases:
          - source-test.radiobretzel

  proxy:
    image: traefik
    command: --web --docker --docker.domain=traefik --logLevel=DEBUG
    networks:
      radiobretzel:
        aliases:
          - traefik.traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml


#  stream:
#    image: radiobretzel/stream:dev
#    build:
#      context: ./../stream
#      dockerfile: ./dockerfiles/dev
#    hostname: stream-test
#    ports:
#      - 8000:8000
#    networks:
#      radiobretzel:
#        aliases:
#          - stream-test.radiobretzel
